<a href="https://colab.research.google.com/github/mazimum86/ANN/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Artificial Neural Network

**Import the libraries**

In [106]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [107]:
tf.__version__

'2.17.0'

## Part 1 - Data Preprocessing

**Importing the dataset**

In [108]:
dataset = pd.read_csv('/content/drive/MyDrive/datasets/Churn_Modelling.csv')
X_ = dataset.iloc[:, 3:-1]
y = dataset.iloc[:, -1].values

In [109]:
X_.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [110]:
print(y)

[1 0 1 ... 1 1 0]


## Encoding Categorical Data

**Tranforming the Geography and Gender Column**

In [111]:
X=pd.get_dummies(X_,drop_first=True,dtype=float).values

In [112]:
print(X)

[[619.  42.   2. ...   0.   0.   0.]
 [608.  41.   1. ...   0.   1.   0.]
 [502.  42.   8. ...   0.   0.   0.]
 ...
 [709.  36.   7. ...   0.   0.   0.]
 [772.  42.   3. ...   1.   0.   1.]
 [792.  28.   4. ...   0.   0.   0.]]


**Splitting the data into training set and test set**

In [113]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

**Feature Scaling**

In [114]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:-3]= sc.fit_transform(X_train[:,:-3])
X_test[:,:-3] = sc.transform(X_test[:,:-3])

In [115]:
X_train[0,:]

array([ 0.16958176, -0.46460796,  0.00666099, -1.21571749,  0.8095029 ,
        0.64259497, -1.03227043,  1.10643166,  0.        ,  1.        ,
        0.        ])

## Part 2 - Building the ANN

**Initializing the ANN**

In [116]:
ann=tf.keras.models.Sequential()

**Adding the input layer and the first hidden layer**

In [117]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

**Adding the second hidden layer**

In [118]:
ann.add(tf.keras.layers.Dense(6,activation='relu'))

**Adding the output layer**

In [119]:
ann.add(tf.keras.layers.Dense(1,activation='sigmoid'))

## Part 3 - Training the ANN Model

**Compiling the ANN**

In [120]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

**Training the ANN on the training set**

In [121]:
ann.fit(X_train,y_train,batch_size=32, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8015 - loss: 0.5052
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7959 - loss: 0.4500
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7962 - loss: 0.4409
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8032 - loss: 0.4241
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8113 - loss: 0.4153
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8085 - loss: 0.4155
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8109 - loss: 0.4006
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8167 - loss: 0.3963
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8165 - loss: 0.3967
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8259 - loss: 0.3940
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8275 - loss: 0.3923
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

## Part 4- Making the predictions and evaluating the model

###Predicting the result of a single observation

**Task**

Use our ANN to predict if our customer with the following details will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to the customer ?

**Solution**

In [122]:
# The dummy variables are found in the last columns after transformation
# France --> 0,0
# Male ---> 1
x = np.array([[
    600,40,3,60000,2,1,1,50000,0,0,1
]])

x[:,:-3]= sc.transform(x[:,:-3])

print(ann.predict(x)>.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
[[False]]


Therefore our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that `France` country was not input as a string in the last column but as "0,0" in the 2 columns before the last. That's because of course the predict method expects the dummy variables of the countries, and as we see in the first row of the matrix of features X, 'France' was encoded as '0,0'.

**Predicting the Test set results**

In [126]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = ann.predict(X_test)
y_pred=(y_pred>.5)
pd.DataFrame(np.concatenate((y_test.reshape(-1,1),y_pred.reshape(-1,1)),1),columns=['Actual','Predicted']).head(10)


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


Actual  Predicted
0       0          0
1       1          0
2       0          0
3       0          0
4       0          0
5       1          1
6       0          0
7       0          0
8       1          0
9       1          1

**Making the Confusion Matrix**

In [127]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1522   73]
 [ 205  200]]


0.861